- name: change route53
  route53:
    state: present
    zone: test.com
    record: www.test.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "f12888c4-b2cc-4dcb-b41b-d87b9ce120c6"
